### ISSUE TITLE
[feature]: Make the original dataset publicly available

### ISSUE THREAD

**Issue by T145** [ThatSINEWAVE/Malicious-URLs-DB#4]
Assuming you want community contributions, having the original dataset to add contributions into rather than just by submitting issues or modifying a generated file would be nice.

My personal recommendation would be to do away with exporting data into a JSON file and have the entire DB in a JSON file.

**Comment by ThatSINEWAVE** [comment]
The original dataset is an Google Sheet that I fill out myself with info from large servers that I moderate, having it open for editing would be a huge risk. 
The main reason I use the JSON as a DB is for the [web interface](https://thatsinewave.github.io/Malicious-URLs-DB) and ease of usage in discord bots and other types of filters.

**Comment by ThatSINEWAVE** [comment]
The only way to have it easier to accept community contributions would be to include the ExporterSheet.xlsx` file inside the repo and accept edits through that

**Comment by T145** [comment]
Sure, then just automate updating the local spreadsheet using GitHub Actions.
